name: Hello

server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: admin
  password: password
  url: jdbc:mysql://localhost:3306/application
