db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
  restart: always
  ports:
  - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_DATABASE: application
    MYSQL_USER: admin
    MYSQL_PASSWORD: password
  volumes:
    - ./script.sql:/docker-entrypoint-initdb.d/script.sql
